#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by "Gradle".
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other POSIX-compliant shell such as ksh or
#       bash, then to run this script, type that shell name before the whole
#       command line, like:
#
#           ksh Gradle
#
#       Calling your script as "sh Gradle" will cause the script to fail if your
#       /bin/sh is noncompliant.
#
#   (2) For Cygwin or MSYS, switch paths to Windows format before running java.
#       If the destination path contains spaces, enclose it in double quotes, and
#       on Windows also add "\" in front of spaces.
#
#   (3) Outlook calendar attachments do not work with Cygwin or MSYS. Instead use
#       a native Windows terminal.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #( absolute
      *)    app_path=$APP_HOME$link ;; #( relative
    esac
done

# This is reliable for all POSIX shells
if [ -z "${APP_HOME-}" ]; then
    APP_HOME=$( cd "${app_path%/*}" > /dev/null && pwd -P ) || exit
fi

JAVA_OPTS="-Xmx64m -Xms64m"
GRADLE_OPTS="${GRADLE_OPTS:-} -Dfile.encoding=UTF-8"

# For Cygwin or MSYS, switch paths to Windows format before running java
if [ "$OSTYPE" = "cygwin" ] || [ "$OSTYPE" = "msys" ]; then
    APP_HOME=$(cygpath --path --mixed "$APP_HOME")
fi

exec "${JAVACMD:-java}" \
    $JAVA_OPTS \
    $GRADLE_OPTS \
    "-Dorg.gradle.appname=$APP_BASE_NAME" \
    -classpath "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" \
    org.gradle.wrapper.GradleWrapperMain \
    "$@"
